In [11]:
import numpy as np
import pandas as pd
df=pd.read_csv("Iris-dataset.csv")

In [12]:
dict_map = {}
index = 1
for i in set(df['y']):
    dict_map[i] = index
    index += 1
dict_map

{'Iris-Virginica': 1, 'Iris-Setosa': 2, 'Iris-Versicolour': 3}

In [13]:
np_df = np.zeros((150,4))
y = []
for i in range(len(df)):
    np_df[i] = df.iloc[i][:4]
    y.append(dict_map[df.iloc[i][-1]])
y_test=np.append(np.append(y[40:50],y[90:100],axis = 0),y[140:150],axis = 0)

In [14]:
train_data= np.append(np.append(np_df[:40],np_df[50:90],axis = 0),np_df[100:140],axis = 0)
train_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
test_data = np.append(np.append(np_df[40:50],np_df[90:100],axis = 0),np_df[140:150],axis = 0)
test_data

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [6]:
mean1 = np.mean(train_data[:40],axis = 0)
mean2 = np.mean(train_data[40:80],axis = 0)
mean3 = np.mean(train_data[80:120],axis = 0)
print(mean1,mean2,mean3)

[5.0375 3.4525 1.46   0.235 ] [6.01   2.78   4.3175 1.35  ] [6.6225 2.96   5.6075 1.99  ]


In [7]:
def tester(test):
   
    r = []
    for i in test:
        dist1 = np.linalg.norm(i-mean1)
        dist2 = np.linalg.norm(i-mean2)
        dist3 = np.linalg.norm(i-mean3)
        r.append([dist1,dist2,dist3,min([dist1,dist2,dist3])])
        
    return r 

In [18]:
a=np.array(tester(test_data))
t=[]
for i in range(30):
    
    if a[i][0]==a[i][3]:
        t.append(2)
    elif a[i][1]==a[i][3]:
        t.append(3)
    else:
        t.append(1)
a

array([[0.1829959 , 3.42728847, 4.93302772, 0.1829959 ],
       [1.28335011, 3.56627344, 5.13334808, 1.28335011],
       [0.7049734 , 3.63267205, 5.17259727, 0.7049734 ],
       [0.39558501, 3.07990361, 4.57343006, 0.39558501],
       [0.58778185, 2.93518419, 4.39286495, 0.58778185],
       [0.51864005, 3.33568677, 4.88694818, 0.51864005],
       [0.38142824, 3.25204647, 4.72099169, 0.38142824],
       [0.50988969, 3.46392931, 5.0055232 , 0.50988969],
       [0.36467451, 3.2575    , 4.72993261, 0.36467451],
       [0.17171925, 3.33538697, 4.8636676 , 0.17171925],
       [3.24275924, 0.56727969, 1.86326662, 0.56727969],
       [3.54266672, 0.37256711, 1.27975095, 0.37256711],
       [2.94804808, 0.44699692, 2.00356245, 0.44699692],
       [2.30227876, 1.55187185, 3.06149677, 1.55187185],
       [3.08617684, 0.43681375, 1.88951383, 0.43681375],
       [3.01371656, 0.42521318, 1.85950598, 0.42521318],
       [3.0636559 , 0.35609865, 1.81982485, 0.35609865],
       [3.29491844, 0.23088146,

In [19]:
l1=[]
for i in range(30):
    if t[i]==y_test[i]:
        l1.append(1)   #1 for accurate
    else:
        l1.append(0)   #0 for inaccurate
l1=np.array(l1)
l1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1])

In [20]:
accuracy=np.sum(l1)/len(a)*100
accuracy

96.66666666666667