In [18]:
import numpy as np
import pandas as pd
import random

In [19]:
datatrain = pd.read_csv("mnist_train.csv")
datatrain

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [5]:
data_train = np.array(datatrain)
data_train

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [6]:
datatest = pd.read_csv("mnist_test.csv")
test_label = datatest['label']
datatest = datatest.drop('label',axis = 1)
test_lable = np.array(test_label)

In [7]:
classes = []
for i in range(10):
    classes.append(data_train[data_train[:,0] == i])
classes[0]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
class1 = []
for i in range(10):
    class1.append(data_train[data_train[:,0] == i])
class1[0]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
sampled = []
for i in range(10):
    for j in range(5):
        sampled.append(np.array(random.sample(list(class1[i]),int(len(class1[i])/5))))
        class1[i] = classes[i]
sampled

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0

In [10]:
mean = {}
for i in range(50):
    mean[f"{i}"] = np.mean(sampled[i][:,1:],axis = 0)
#mean

In [11]:
data_test = np.array(datatest)
data_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
lst = []
for i in range(10):
    for j in range(5):
        lst.append(i)
lst = np.array(lst)

distance = []
index = 0
output = []
for i in range(10):
    for j in range(5):
        distance.append(np.linalg.norm(data_test[1] - mean[f'{index}']))
        index += 1

In [13]:
final_output = []
for k in range(10000):
    
    distance = []
    index = 0
    output = []
    for i in range(10):
        for j in range(5):
            distance.append(np.linalg.norm(data_test[k] - mean[f'{index}']))
            index += 1
    distance = np.array(distance)
    distance = np.stack((distance,lst),axis = 1)
    distance = distance.astype("int64")
    distance = distance[distance[:,0].argsort()]
    output = distance[:5]
    output
    var = 0
    
    for j in range(5):
        for n in output[:,1]:
            if np.count_nonzero(output[:,1]== n) > 1:
                var = n
            else:
                var = n
    final_output.append(n)
# final_output

In [14]:
count = 0
for i in range(10000):
    if final_output[i] == test_label[i]:
        count = count + 1
total_accuracy= count/10000*100
total_accuracy

81.17999999999999

In [15]:
final_arr = np.stack((final_output,test_label),axis = 1)
final_arr

array([[7, 7],
       [2, 2],
       [1, 1],
       ...,
       [4, 4],
       [8, 5],
       [6, 6]], dtype=int64)

In [16]:
wrong_ans = []
for n in final_arr:
    if n[0] != n[1]:
        wrong_ans.append(n[1])
wrong_ans.sort()
# wrong_ans

In [17]:
iterate = {0,1,2,3,4,5,6,7,8,9}
for i in iterate:
    w_occurence = wrong_ans.count(i)
    r_occurance = list(test_label).count(i)
    print("class:",i," accuracy:", 100-(w_occurence/r_occurance*100))

class: 0  accuracy: 87.85714285714286
class: 1  accuracy: 96.12334801762114
class: 2  accuracy: 74.41860465116278
class: 3  accuracy: 80.1980198019802
class: 4  accuracy: 82.4847250509165
class: 5  accuracy: 66.59192825112108
class: 6  accuracy: 85.28183716075156
class: 7  accuracy: 82.78210116731518
class: 8  accuracy: 73.40862422997947
class: 9  accuracy: 79.38553022794846
